import React, { useState } from 'react';
import { 
  Gamepad2, Volume2, VolumeX, ArrowLeft,
  Grid, Compass, Info, Award, HelpCircle,
  FileText, Activity, Layers, Edit3, ShieldAlert, Users, User,
  Zap, Lock, Swords, Terminal, Search
} from 'lucide-react';
import { playSound, setMuted, getMuted } from './utils/audio';
import { useAuth } from './context/AuthContext';

// Import game components
import Memory from './components/Memory';
import Rps from './components/Rps';
import Tictactoe from './components/Tictactoe';
import Scribbles from './components/Scribbles';

import Eightpuzzle from './components/Eightpuzzle';
import Numberguess from './components/Numberguess';
import Zip from './components/Zip';
import Sudoku from './components/Sudoku';
import Typing from './components/Typing';
import Neonrunner from './components/Neonrunner';
import Nodehack from './components/Nodehack';
import Wordsearch from './components/Wordsearch';
import Numberquest from './components/Numberquest';

// Import auth/lobby components
import AuthScreens from './components/AuthScreens';
import MultiplayerLobby from './components/MultiplayerLobby';

const GAMES = [
  {
    id: 'memory',
    title: 'Memory Match',
    description: 'Classic green felt card table. Match cards in fewer moves and beat the clock!',
    icon: Layers,
    component: Memory,
    color: 'var(--primary)',
    category: 'Casual',
    multiplayer: true
  },
  {
    id: 'rps',
    title: 'Rock Paper Scissors',
    description: 'Battle the CPU. Keep win streaks and counter AI choices in advanced mode.',
    icon: Gamepad2,
    component: Rps,
    color: 'var(--accent)',
    category: 'Arcade',
    multiplayer: true
  },
  {
    id: 'tictactoe',
    title: 'Tic-Tac-Toe',
    description: 'Challenge our unbeatable AI opponent. A neat visual grid with neon sparks.',
    icon: Grid,
    component: Tictactoe,
    color: 'var(--secondary)',
    category: 'Strategy',
    multiplayer: true
  },
  {
    id: 'scribbles',
    title: 'Scribbles Canvas',
    description: 'Interactive sketch board. Draw the prompt generated by the server and download your art.',
    icon: Edit3,
    component: Scribbles,
    color: 'var(--info)',
    category: 'Creative',
    multiplayer: true
  },

  {
    id: 'eightpuzzle',
    title: '8-Puzzle Solver',
    description: 'Sliding tile puzzle. Solves instantly with step-by-step automated solver playback!',
    icon: Compass,
    component: Eightpuzzle,
    color: 'var(--info)',
    category: 'Puzzle',
    multiplayer: false
  },
  {
    id: 'numberguess',
    title: 'Smart Guessing',
    description: 'Guess the hidden number. Includes hot/cold thermometer indicator and search estimation.',
    icon: HelpCircle,
    component: Numberguess,
    color: 'var(--accent)',
    category: 'Logic',
    multiplayer: true
  },
  {
    id: 'numberquest',
    title: 'Number Quest',
    description: 'Wordle for numbers. Guess the 5-digit code in 6 chances with color-coded hints!',
    icon: Trophy,
    component: Numberquest,
    color: 'var(--primary)',
    category: 'Logic',
    multiplayer: true
  },
  {
    id: 'zip',
    title: 'ZIP Connection',
    description: 'Connect scattered digits in the grid in ascending order. Follow the laser paths!',
    icon: FileText,
    component: Zip,
    color: 'var(--secondary)',
    category: 'Mind',
    multiplayer: false
  },
  {
    id: 'sudoku',
    title: 'Sudoku Solver',
    description: 'Interactive Sudoku with dynamic validation, hints, and automatic backtrack solving.',
    icon: Award,
    component: Sudoku,
    color: 'var(--info)',
    category: 'Mind',
    multiplayer: false
  },
  {
    id: 'typing',
    title: 'Typing Showdown',
    description: 'Test typing speed and accuracy in real-time. Highlights mistakes and charts speed metrics.',
    icon: Activity,
    component: Typing,
    color: 'var(--primary)',
    category: 'Speed',
    multiplayer: false
  },
  {
    id: 'neonrunner',
    title: 'Neon Runner',
    description: 'Dodge incoming energy barriers and collect data bits at high speed down three neon lanes.',
    icon: Zap,
    component: Neonrunner,
    color: 'var(--primary)',
    category: 'Arcade',
    multiplayer: false
  },


  {
    id: 'nodehack',
    title: 'Hack the Node',
    description: 'Tug-of-war trivia battle. Answer questions correctly to pull the node closer to your terminal.',
    icon: Terminal,
    component: Nodehack,
    color: 'var(--secondary)',
    category: 'Trivia',
    multiplayer: true
  },
  {
    id: 'wordsearch',
    title: 'Word Search Grid',
    description: 'Find the hidden words in the grid. Drag across letters in any of the 8 directions.',
    icon: Search,
    component: Wordsearch,
    color: 'var(--accent)',
    category: 'Puzzle',
    multiplayer: false
  }
];

function App() {
  const { user, loading, checkUser } = useAuth();
  const [view, setView] = useState('DASHBOARD'); // 'DASHBOARD', 'GAME', 'LOBBY', 'ONLINE_GAME'
  const [selectedGame, setSelectedGame] = useState(null);
  const [activeRoomId, setActiveRoomId] = useState(null);
  const [activeOnlineGame, setActiveOnlineGame] = useState(null);
  const [muted, setMutedState] = useState(getMuted());

  React.useEffect(() => {
    const handleBeforeUnload = (e) => {
      e.preventDefault();
      e.returnValue = '';
      return '';
    };
    window.addEventListener('beforeunload', handleBeforeUnload);
    return () => {
      window.removeEventListener('beforeunload', handleBeforeUnload);
    };
  }, []);

  const handleSelectGame = (game) => {
    playSound('click');
    setSelectedGame(game);
    setView('GAME');
  };

  const handleBackToDashboard = () => {
    playSound('click');
    setSelectedGame(null);
    setView('DASHBOARD');
  };

  const toggleMute = () => {
    const nextMuted = !muted;
    setMuted(nextMuted);
    setMutedState(nextMuted);
    if (!nextMuted) {
      playSound('click');
    }
  };

  const handleEnterLobby = () => {
    playSound('click');
    setView('LOBBY');
  };

  const handleLaunchOnlineRoom = (roomId, gameTypeId) => {
    const game = GAMES.find(g => g.id === gameTypeId);
    if (game) {
      setActiveRoomId(roomId);
      setActiveOnlineGame(game);
      setView('ONLINE_GAME');
    }
  };

  const handleLeaveOnlineRoom = (force = false) => {
    if (force !== true) {
      const confirmExit = window.confirm("Are you sure you want to exit the room? This will abandon the match.");
      if (!confirmExit) return;
    }
    playSound('click');
    if (activeRoomId) {
      fetch(`${window.API_BASE_URL}/api/room/${activeRoomId}/abandon/`, {
        method: 'POST',
        credentials: 'include'
      }).catch(err => console.warn("Error calling abandon room:", err));
    }
    setActiveRoomId(null);
    setActiveOnlineGame(null);
    setView('LOBBY');
    if (checkUser) checkUser();
  };

  if (loading) {
    return (
      <div className="app-container" style={{ justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
        <div style={{ color: 'var(--primary)', fontSize: '1.5rem', fontWeight: 800, textShadow: '0 0 10px var(--primary-glow)', letterSpacing: '1px' }}>
          GRID SYSTEM INITIALIZING...
        </div>
      </div>
    );
  }

  return (
    <div className="app-container">
      <header className="arcade-header">
        <div className="brand" onClick={handleBackToDashboard} style={{ cursor: 'pointer' }}>
          <Gamepad2 size={32} color="var(--primary)" />
          <span>NEONGRID</span>ARCADE
        </div>
        
        <div className="header-controls">
          {user ? (
            <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', fontSize: '0.9rem' }}>
              <span style={{ color: 'var(--text-muted)' }}>
                Pilot: <strong style={{ color: 'var(--primary)' }}>{user.name}</strong>
              </span>
              <span style={{ color: 'var(--text-muted)', display: 'flex', gap: '0.6rem', borderLeft: '1px solid var(--glass-border)', paddingLeft: '1rem' }}>
                <span style={{ color: 'var(--primary)' }}>W: <strong>{user.wins}</strong></span>
                <span style={{ color: 'var(--accent)' }}>L: <strong>{user.losses}</strong></span>
                <span>T: <strong>{user.ties}</strong></span>
              </span>
              {view !== 'LOBBY' && view !== 'ONLINE_GAME' && (
                <button className="btn-primary" onClick={handleEnterLobby} style={{ padding: '0.4rem 1rem', fontSize: '0.8rem' }}>
                  Open Lobby
                </button>
              )}
            </div>
          ) : (
            view !== 'LOBBY' && (
              <button className="btn-secondary" onClick={handleEnterLobby} style={{ padding: '0.4rem 1rem', fontSize: '0.8rem' }}>
                Online Portal
              </button>
            )
          )}
          
          <button className="btn-icon" onClick={toggleMute} title={muted ? "Unmute" : "Mute"}>
            {muted ? <VolumeX size={20} /> : <Volume2 size={20} />}
          </button>
        </div>
      </header>

      {view === 'DASHBOARD' && (
        <main className="dashboard-main">
          {/* Neon Banner for Multiplayer Lobby */}
          <div 
            className="game-card lobby-banner-card" 
            onClick={handleEnterLobby}
          >
            <div className="lobby-banner-left">
              <div className="game-icon-container" style={{ color: 'var(--primary)', marginBottom: 0 }}>
                <Users size={32} />
              </div>
              <div>
                <h3 className="game-title" style={{ color: 'var(--primary)' }}>MULTIPLAYER NEON LOBBY</h3>
                <p className="game-description" style={{ marginBottom: 0 }}>
                  {user 
                    ? `Connected as ${user.email}. Challenge other pilots, view win/loss records, and launch synced matches! [Stats: ${user.wins} Wins, ${user.losses} Losses, ${user.ties} Ties]` 
                    : "Establish net connection, authorize your codename, and challenge real-time players by email!"
                  }
                </p>
              </div>
            </div>
            <div className="play-badge" style={{ color: 'var(--primary)', fontWeight: 800 }}>
              Enter Lobby &rarr;
            </div>
          </div>

          <div className="hero-section">
            <h1>NEONGRID ARCADE</h1>
            <p>Ready to enter the grid? 10 premium retro-neon gaming modules designed and developed by Vraj. Let the games begin!</p>
          </div>

          <div className="game-grid">
            {GAMES.filter(g => g.id !== 'scribbles' && g.id !== 'nodehack').map((game) => {
              const IconComp = game.icon;
              return (
                <div 
                  key={game.id} 
                  className="game-card"
                  onClick={() => handleSelectGame(game)}
                >
                  <div>
                    <div className="game-icon-container" style={{ color: game.color }}>
                      <IconComp size={28} />
                    </div>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                      <h3 className="game-title">{game.title}</h3>
                      <span style={{ 
                        fontSize: '0.75rem', 
                        padding: '0.2rem 0.6rem', 
                        borderRadius: '20px', 
                        background: 'rgba(255,255,255,0.04)',
                        border: '1px solid var(--glass-border)',
                        color: 'var(--text-muted)'
                      }}>
                        {game.category}
                      </span>
                    </div>
                    <p className="game-description">{game.description}</p>
                  </div>
                  <div className="play-badge">
                    Play Solo &rarr;
                  </div>
                </div>
              );
            })}
          </div>
        </main>
      )}

      {view === 'GAME' && selectedGame && (
        <main className="game-view">
          <div className="back-header">
            <button className="btn-back" onClick={handleBackToDashboard}>
              <ArrowLeft size={16} /> Back to Hub
            </button>
            <div className="game-header-info">
              <h2>{selectedGame.title}</h2>
            </div>
          </div>
          <div className="game-container-card">
            <selectedGame.component />
          </div>
        </main>
      )}

      {view === 'LOBBY' && (
        <main className="game-view">
          <div className="back-header">
            <button className="btn-back" onClick={handleBackToDashboard}>
              <ArrowLeft size={16} /> Exit Lobby
            </button>
            <div className="game-header-info">
              <h2>Multiplayer Portal</h2>
            </div>
          </div>
          {user ? (
            <MultiplayerLobby onLaunchRoom={handleLaunchOnlineRoom} />
          ) : (
            <div style={{ display: 'flex', justifyContent: 'center', width: '100%' }}>
              <AuthScreens />
            </div>
          )}
        </main>
      )}

      {view === 'ONLINE_GAME' && activeOnlineGame && (
        <main className="game-view">
          <div className="back-header">
            <button className="btn-back" onClick={handleLeaveOnlineRoom}>
              <ArrowLeft size={16} /> Exit Room
            </button>
            <div className="game-header-info">
              <h2>Online Match: {activeOnlineGame.title}</h2>
            </div>
          </div>
          <div className="game-container-card">
            <activeOnlineGame.component 
              roomId={activeRoomId} 
              isOnline={true} 
              onBack={handleLeaveOnlineRoom} 
            />
          </div>
        </main>
      )}
    </div>
  );
}

export default App;
